public enum Monster
{
    BeholderGuardian,
    BeholderQueen,
    DarkKnightWarrior,
    DarkKnightMistress,
    MimicBrute,
    MimicSiren,
    ShellCrabWarrior,
    ShellCrabMatriarch,
    WingedDemonWarrior,
    WingedDemonSorceress,
    ReptilianWarrior,
    ReptilianQueen,
    RodentAssassin,
    RodentMistress,
    PhantomWraith,
    PhantomSorceress,
    LycanthropeAlpha,
    LycanthropeBeta
}